name: aries_designs
description: A component library that implements the Sirius design system.
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  storybook_flutter: ^0.14.0
  styled_text: ^8.1.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/icons/no-document.png
    - assets/images/logos/logo.png
  uses-material-design: true
