// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDh6tOp9uSK2Id8UW0AT6nDWND9Hnhfs4',
    appId: '1:302103377027:web:e0c1f7afbd8c288f9cd7b6',
    messagingSenderId: '302103377027',
    projectId: 'finaproject-twitter',
    authDomain: 'finaproject-twitter.firebaseapp.com',
    storageBucket: 'finaproject-twitter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD95C5lddNaMO7SYMWP8hxm104muZDZ7FU',
    appId: '1:302103377027:android:54f6e96d8eb6e61e9cd7b6',
    messagingSenderId: '302103377027',
    projectId: 'finaproject-twitter',
    storageBucket: 'finaproject-twitter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-z8E77PRwRX0XMK-nj7PX6J4iiCgyG-0',
    appId: '1:302103377027:ios:17b06bbb4271e1c79cd7b6',
    messagingSenderId: '302103377027',
    projectId: 'finaproject-twitter',
    storageBucket: 'finaproject-twitter.appspot.com',
    iosClientId: '302103377027-ersljn3jj9phg8s5s418pov8mcf3c0rm.apps.googleusercontent.com',
    iosBundleId: 'vn.glints.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-z8E77PRwRX0XMK-nj7PX6J4iiCgyG-0',
    appId: '1:302103377027:ios:17b06bbb4271e1c79cd7b6',
    messagingSenderId: '302103377027',
    projectId: 'finaproject-twitter',
    storageBucket: 'finaproject-twitter.appspot.com',
    iosClientId: '302103377027-ersljn3jj9phg8s5s418pov8mcf3c0rm.apps.googleusercontent.com',
    iosBundleId: 'vn.glints.finalproject',
  );
}
